attention_manager:
  ros__parameters:
    clients:
      - table_attention_client
      - zone_attention_client
    robot_name: r2d2
    strategy: simple

table_attention_client:
  ros__parameters:
    class_id: table
    instances: ["default"]
    default:
      - "0.5, 0.15, 0.75"
      - "0.5, -0.15, 0.75"
      - "0.0, 0.15, 0.75"
      - "0.0, -0.15, 0.75"
      - "-0.5, 0.15, 0.75"
      - "-0.5, -0.15, 0.75"
      - "0.4, 0.6, 1.00"
      - "0.4, -0.6, 1.00"
      - "-0.4, 0.6, 1.00"
      - "-0.4, -0.6, 1.00"

zone_attention_client:
  ros__parameters:
    class_id: zone
    instances: ["waiting_zone"]
    default:
      - "8.0, 8.0, 8.0"
      - "9.0, 9.0, 9.0"
    waiting_zone:
      - "1.0, 1.0, 0.0"
      - "1.0, -1.0, 0.0"
      - "-1.0, 1.0, 0.0"
      - "-1.0, -1.0, 0.0"
